### ISSUE TITLE
ignore https errors

### ISSUE THREAD

**Issue by riksnelders** [nesk/puphpeteer#11]
title says it all, is there an option for it?

**Comment by llevering** [comment]
Look for the option: ignoreHTTPSErrors in the Puppeteer docs:
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md

When using request interception there were some errors in the Puppeteer api, don't know if that is fixed already.

**Comment by nesk** [comment]
Thank you @llevering for answering.

@riksnelders For those kind of questions, I recommend you to ask them [on Stackoverflow with the _puppeteer_ tag](https://stackoverflow.com/questions/tagged/puppeteer?sort=newest&pageSize=50). Posting in Github issues should be reserved for bug reports. 🙂
