### ISSUE TITLE
Wait on document loaded, Javascript 

### ISSUE THREAD

**Issue by riksnelders** [nesk/puphpeteer#12]

**Comment by riksnelders** [comment]
This is not working though.
```
   $puppeteer = new Puppeteer([
            'read_timeout' => 65, // In seconds

        ]);
        $browser = $puppeteer->launch(['ignoreHTTPSErrors'=>true]
        );

        $page = $browser->newPage();
        $page->goto('http://chartjs.org', [
            'timeout' => 10000, // In milliseconds=
        ]);
        $page->waitForNavigation('domcontentloaded');


        $page->screenshot(['path' => storage_path('example.png')]);

```

**Comment by nesk** [comment]
@riksnelders [Puppeteer's documentation](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-pagewaitfornavigationoptions) says:

> This resolves when the page navigates to a new URL or reloads.

You have to use `waitForNavigation` _before_ navigating to a new page. Also, [this method takes an object for the first parameter](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-pagewaitfornavigationoptions), not a string.
