### ISSUE TITLE
Browser Closes Automatically

### ISSUE THREAD

**Issue by hughsaffar** [nesk/puphpeteer#13]
I am just wondering if there is a way to stop the browser from closing automatically.
Currently, even if I do not call ``` $browser->close(); ``` the browser will close.

**Comment by nesk** [comment]
This is due [to the `idle_timeout` option](https://github.com/nesk/rialto/blob/76db20968e3ed710e66e6c495a04f25f1ccb6408/docs/api.md#options) being set to `60` by default. You can set it to a higher value, which is recommended if you want to change this value for a production environment, or you can also set it to `0` if you want to disable the timeout, however this should be used only for development environments.

**Comment by kids-return** [comment]
```php
        $puppeteer = new Puppeteer(['idle_timeout' => 3600]);
        $browser = $puppeteer->launch(['headless' => false]);
        $page = $browser->newPage();
        $page->goto('https://example.com');
```
The browser will still close immediately after it is opened.

**Comment by nesk** [comment]
This is perfectly normal, PHP ends its script once the page is loaded. If you want to keep the browser open, you will have to keep PHP running, this could be done, for example, with [the `sleep()` function](http://php.net/sleep).

**Comment by leocavalcante** [comment]
Added a `while (true);` at the end of script hehe.
