### ISSUE TITLE
Size limitations in JsFunction?

### ISSUE THREAD

**Issue by systemaddict** [nesk/puphpeteer#16]
Hi

I'm trying to get the complete HTML but it's returning null.

```php
$puppeteer = new Puppeteer;
$browser = $puppeteer->launch();

$page = $browser->newPage();

$page->goto( 'https://google.com' );

$page->waitFor(5000);

$page_meta = $page->evaluate(JsFunction::create("   
    return {
        body: document.body.innerHTML
    };
"));

var_dump( $page_meta );
```

It will work with this:

```php
$page_meta = $page->evaluate(JsFunction::create("   
    return {
        body: document.querySelector('#main').innerHTML
    };
"));
```

**Comment by nesk** [comment]
Just tried the two versions of your code and everything is running fine with the latest version of PuPHPeteer.

What version of PuPHPeteer are you using? What are the versions of PHP/Node?

And [provide some logs](https://github.com/nesk/puphpeteer/blob/master/.github/contributing.md#provide-logs-with-your-bug-report) please.

**Comment by nesk** [comment]
Actually, now I remember, PuPHPeteer had a size limitation. This was a bug and was fixed since v0.2.1, please upgrade to the latest version (currently, v1.1.0).

**Comment by systemaddict** [comment]
Hi Nesk. The result is the same. Please close this issue. I will try on another server and reopen with better info if it persists.

**Comment by nesk** [comment]
What I can also suggest you is to try in a VM, and if the bug persists you only have to send me the VM so I can try myself. 😉

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
