### ISSUE TITLE
Chromium not responding.

### ISSUE THREAD

**Issue by quocthinh212** [nesk/puphpeteer#18]
Firstly thank for you help full library :).

I have problem when test with this link 
"https://agents.vietjetair.com/sitelogin.aspx?lang=vi"
I try it with puppeteer (Node js,) it work properly but when i try with your library the browser is not responding. 

Please help me fix this issue.

Tks,

**My code**
```php
puppeteer = new Puppeteer();
            $search  = "https://agents.vietjetair.com/sitelogin.aspx?lang=vi";
            $browser = $puppeteer->launch([
                'headless' => false,
                'devtools' => true,
                'slowMo'   => 250,
                'args'     => ['--no-sandbox', '--disable-setuid-sandbox',
            ]);
            $page = $browser->newPage();
            $page->tryCatch->goto($search);
           $page->waitForSelector('#TrvOptGridHdr');
            $html = $page->content();
            $browser->close();
```

**Generated logs**

```
TimeoutError: waiting for selector "#TrvOptGridHdr" failed: timeout 30000ms exceeded\n
    at new WaitTask (/Users/mac/Documents/Project/Git/Laravel/12bot/node_modules/puppeteer/lib/FrameManager.js:864:28)\n
    at Frame._waitForSelectorOrXPath (/Users/mac/Documents/Project/Git/Laravel/12bot/node_modules/puppeteer/lib/FrameManager.js:755:12)\n
    at Frame.waitForSelector (/Users/mac/Documents/Project/Git/Laravel/12bot/node_modules/puppeteer/lib/FrameManager.js:713:17)\n
    at Page.waitForSelector (/Users/mac/Documents/Project/Git/Laravel/12bot/node_modules/puppeteer/lib/Page.js:1017:29)\n
    at Instruction.callResourceMethod (/Users/mac/Documents/Project/Git/Laravel/12bot/vendor/nesk/rialto/src/node-process/Instruction.js:186:40)\n
    at Instruction.execute (/Users/mac/Documents/Project/Git/Laravel/12bot/vendor/nesk/rialto/src/node-process/Instruction.js:161:31)\n
    at PuppeteerConnectionDelegate.handleInstruction (/Users/mac/Documents/Project/Git/Laravel/12bot/vendor/nesk/puphpeteer/src/PuppeteerConnectionDelegate.js:3 ▶
    at Connection.handleSocketData (/Users/mac/Documents/Project/Git/Laravel/12bot/vendor/nesk/rialto/src/node-process/Connection.js:64:23)\n
    at Socket.socket.on.data (/Users/mac/Documents/Project/Git/Laravel/12bot/vendor/nesk/rialto/src/node-process/Connection.js:48:18)\n
    at Socket.emit (events.js:182:13)
```

**Screenshots**
![screen shot 2018-08-11 at 07 14 27](https://user-images.githubusercontent.com/14103334/43985975-402df980-9d36-11e8-938f-d135397d9b39.png)

**Environment :**
 - OS:  MacOS 10.13.6,]
 - Node version: [10.0.0]
 - PHP version [7.2.6]

**Comment by nesk** [comment]
You say it works with Puppeteer, however, I'm unable to make this code work:

```js
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        headless: false,
        devtools: true,
        slowMo: 250,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });

    const page = await browser.newPage()

    await page.goto('https://agents.vietjetair.com/sitelogin.aspx?lang=vi');
    await page.waitForSelector('#TrvOptGridHdr');

    const content = await page.content();

    console.log(content);
})();
```

I get the following error when running it:

```shell
(node:45267) UnhandledPromiseRejectionWarning: Error: waiting for selector "#TrvOptGridHdr" failed: timeout 30000ms exceeded
    at new WaitTask (/Users/johann/Development/puphpeteer/node_modules/puppeteer/lib/FrameManager.js:840:28)
    at Frame._waitForSelectorOrXPath (/Users/johann/Development/puphpeteer/node_modules/puppeteer/lib/FrameManager.js:731:12)
    at Frame.waitForSelector (/Users/johann/Development/puphpeteer/node_modules/puppeteer/lib/FrameManager.js:690:17)
    at Page.waitForSelector (/Users/johann/Development/puphpeteer/node_modules/puppeteer/lib/Page.js:1008:29)
    at /Users/johann/Development/puphpeteer/test.js:14:16
```

And if I open the website in a browser and check for the existence of a `#TrvOptGridHdr` element, I get nothing (see the top right of the image):

<img width="1452" alt="image" src="https://user-images.githubusercontent.com/817508/43991780-fe94b566-9d73-11e8-95c3-fd00242e8996.png">

You can provide me a working example in JS and I will try to make it work with PuPHPeteer. 🙂

**Comment by quocthinh212** [comment]
@nesk  sorry sir. 
This line is wrong. if browser redirect to vietjetair.com then browser was work properly.
```php
await page.waitForSelector('#TrvOptGridHdr');
````
Please try again with new php code in headless = false, 
The browser will open and work with first link. In second link. Browser will crash (Not respoding).

```php
try {

            $puppeteer = new Puppeteer([
                'debug' => true, 
            ]);
            $search  = "https://vietjetair.com";
            $browser = $puppeteer->launch([
                'headless' => false,
                'devtools' => true,
                'args'     => ['--no-sandbox', '--disable-setuid-sandbox'],
            ]);

            $page = $browser->newPage();

            $page->tryCatch->goto("https://www.vietjetair.com/Sites/Web/vi-VN/Home");
          //goto click agent
            $page->tryCatch->goto("https://agents.vietjetair.com/sitelogin.aspx?lang=vi");

            $page->waitForNavigation();

            $page->waitForSelector('#txtAgentPswd');
            $html = $page->content();
            $browser->close();
            
            return $html;

        } catch (Node\Exception $exception) {

            return $exception->getMessage();
        }
```

**Comment by nesk** [comment]
Well, sorry but I honestly don't understand what you're trying to do. 😅

You said:

> I try it with puppeteer (Node js,) it work properly but when i try with your library the browser is not responding.

Provide me the JS code you used to make it work, and then I will try to make it work in PHP. Is it ok for you?

**Comment by quocthinh212** [comment]
@nesk 😅  This is my JS code:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();

  await page.goto(
    `https://booking.vietjetair.com/SearchResCheckin.aspx?lang=vi`,
  );

  await page.waitForSelector('#txtSearchResNum');
  const content = await page.content();
  console.log(content);

  await browser.close();
  
})();
```

**Comment by nesk** [comment]
Is this what you want? It works great for me.

```php
$puppeteer = new Nesk\Puphpeteer\Puppeteer;

$browser = $puppeteer->launch(['headless' => false]);
$page = $browser->newPage();

$page->goto('https://booking.vietjetair.com/SearchResCheckin.aspx?lang=vi');
$page->waitForSelector('#txtSearchResNum');

$content = $page->content();
var_dump($content);
```

I think the issue in your PHP code was the call to `$page->waitForNavigation();`, I don't know why you added this since you didn't need it in the original JS script. FYI, [this method has some issues with PuPHPeteer](https://github.com/nesk/puphpeteer/issues/4), so don't use it for the moment. 😉

**Comment by quocthinh212** [comment]
I don't know why but when i try your code browser will not responding :(

<img width="1778" alt="screen shot 2018-08-11 at 20 59 31" src="https://user-images.githubusercontent.com/14103334/43992523-a7c6bf6e-9da9-11e8-8479-241c229e21e4.png">

**Comment by nesk** [comment]
The only reason I can think of is maybe your Internet connection is too slow and you have to increase the timeout of the `waitForSelector` method?

```php
$puppeteer = new Nesk\Puphpeteer\Puppeteer([
    'idle_timeout' => 240,
    'read_timeout' => 240,
]);

$browser = $puppeteer->launch(['headless' => false]);
$page = $browser->newPage();

$page->goto('https://booking.vietjetair.com/SearchResCheckin.aspx?lang=vi');
$page->waitForSelector('#txtSearchResNum', ['timeout' => 200]);

$content = $page->content();
var_dump($content);
```

**Comment by quocthinh212** [comment]
I think internet connection is not reason because JS script work properly. 
I use your lib in my Laravel project. :( I push code to my VPS (centos) but i have same problem with local mac.
Please view my screen video. You can see detail error
https://www.youtube.com/watch?v=i2j6dCabMgI
Thanks you so much

**Comment by nesk** [comment]
@quocthinh212 It seems like you solved your issue? Can you explain me how?

Also, why did you remove all your comments? This issue now can no longer benefit to anyone. 😕

**Comment by quocthinh212** [comment]
@nesk  error occurred due to nginx on my mac (install  via homebrew).
I try with php -S localhost:8000 it work fine. I don't know why but i think have problems between nginx and chromium :(. And this only happen when php open browser (Not in headless mode).

I remove all my comments because a this website link (VJ) can not public :(.  
Thanks for your helpful library. :)
