### ISSUE TITLE
Error: Cannot find module 'lodash' at Function.Module._resolveFilename

### ISSUE THREAD

**Issue by roselan** [nesk/puphpeteer#20]
When calling puphpeteer by running the default example, a mighty error shows up. It wraps a js error: "Error: Cannot find module 'lodash' at Function.Module._resolveFilename".

To solve it run "npm install" in both "\vendor\nesk\rialto" and "\vendor\nesk\puphpeteer"

windows server 2016 standard
puphpeteer 1.3.0
node 10.10
php 7.2.8
npm

**Comment by nesk** [comment]
You probably didn't run `npm install @nesk/puphpeteer` in your project directory, this is a requirement.
