### ISSUE TITLE
net::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by Jaspur** [nesk/puphpeteer#26]
**Describe the bug**
Getting Certificate Authority failures:

```
 production.ERROR: net::ERR_CERT_AUTHORITY_INVALID at http://jaspur.nl {"exception":"[object] (Nesk\\Rialto\\Exceptions\\Node\\FatalException(code: 0): net::ERR_CERT_AUTHORITY_INVALID at http://jaspur.nl at /home/foobar.com/vendor/nesk/rialto/src/ProcessSupervisor.php:307)
```

**Reproducible example**
```php
$puppeteer = new Puppeteer;
$browser   = $puppeteer->launch();

$page = $browser->newPage();
$page->goto($url = 'http://jaspur.nl');
$page->screenshot(['path' => 'example.png');

$browser->close();
```

**Expected behavior**
A Screenshot

**Error logs**

```
 production.ERROR: net::ERR_CERT_AUTHORITY_INVALID at http://jaspur.nl {"exception":"[object] (Nesk\\Rialto\\Exceptions\\Node\\FatalException(code: 0): net::ERR_CERT_AUTHORITY_INVALID at http://jaspur.nl at /home/foobar.com/vendor/nesk/rialto/src/ProcessSupervisor.php:307)
```

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Node version: v8.1.0
 - PHP version: 7.2.10

My Node package manager is:
 - [x] NPM (specify the version)
 - [ ] Yarn (specify the version)
 - [ ] Other (specify the name and version)

@nesk

**Comment by nesk** [comment]
Use the [`ignoreHTTPSErrors`](https://pptr.dev/#?product=Puppeteer&version=v1.9.0&show=api-puppeteerlaunchoptions) option.

**Comment by Jaspur** [comment]
How?

**Comment by nesk** [comment]
See the link I've provided in my previous message. 😉

**Comment by Jaspur** [comment]
Yea, but when I do:
```
$browser   = $puppeteer->launch(['ignoreHTTPSErrors' => true]);
```
Then this is the result:
![unbbix httpsjaspurnl](https://user-images.githubusercontent.com/4254854/47358170-48072b00-d6c9-11e8-9799-7e5d553ffd4e.png)

**Comment by nesk** [comment]
Actually, I don't think this is related to Puppeteer or my project, maybe to your firewall configuration, or your OS? Did you try to run this script with Puppeteer (in JS)?
