### ISSUE TITLE
Add doc blocs to help IDE static analysis

### ISSUE THREAD

**Issue by jonnywilliamson** [nesk/puphpeteer#27]
**Describe the bug**
When using the library with PHPStorm etc I get lots of "warnings" that certain methods are not found. It also prevents autocomplete from working.

![image](https://user-images.githubusercontent.com/2513663/47301263-6a8c3c00-d616-11e8-8058-c2d97de1a757.png)

Would you be open to any PRs that add docblocks to parts of the library to get rid of these slightly annoying warnings?

**Comment by nesk** [comment]
I like the idea, this could be done with the [`@method`](https://docs.phpdoc.org/references/phpdoc/tags/method.html) phpDoc tag. However, I'm not willing to maintain this, it is too much work and I fear to have non-up-to-date definitions.

I don't use PhpStorm bu it seems like [you can disable those errors](https://stackoverflow.com/a/26314659/1513045).
