### ISSUE TITLE
reading socket timeout

### ISSUE THREAD

**Issue by SergeyMiracle** [nesk/puphpeteer#31]
Need a little help here, can't figure our where to i can tweak this option, if there is one:

`The timeout (30.000 seconds) has been exceeded while reading the socket of the process. Maybe you should increase the "read_timeout" option. {"exception":"[object] (Nesk\\Rialto\\Exceptions\\ReadSocketTimeoutException(code: 0): The timeout (30.000 seconds) has been exceeded while reading the socket of the process. Maybe you should increase the \"read_timeout\" option. at /vendor/nesk/rialto/src/ProcessSupervisor.php:431, Socket\\Raw\\Exception(code: 11): Socket operation failed: Resource temporarily unavailable (SOCKET_EAGAIN) at /vendor/clue/socket-raw/src/Exception.php:55)`

**Comment by SergeyMiracle** [comment]
Ok. found it. NVM

**Comment by Ya-hui** [comment]
请问怎么解决的?

**Comment by markozivanovic** [comment]
Increasing the option passed when creating a new puphpeteer, like in the example below:

`$puppeteer = new Puppeteer([
	'read_timeout' => 120, // In seconds
]);`

**Comment by DengSihan** [comment]
> Ok. found it. NVM

Sorry for interrupting. 
Counld you please be more detailed, where to set the `read_timeout` config?
Thanks a lot.

**Comment by markozivanovic** [comment]
Take a look at my previous comment. You pass the read_timeout option when creating the new puppeteer object.

**Comment by DengSihan** [comment]
> Take a look at my previous comment. You pass the read_timeout option when creating the new puppeteer object.

Thanks a lot!
I created the new puppeteer object like code below and it works.
```php
$puppeteer = new Puppeteer([
    'read_timeout' => 9000,
    'idle_timeout' => 9000
]);
```

**Comment by ernst77** [comment]
I had this issue as well and increasing any of the timeouts didn't work... I figured it out it was caused by css font loading in header/footer html from url. So removing `@import url('http://....')` from header/footer html fixed the issue.

**Comment by superinterstella555** [comment]
@ErnestStaug I have the same problem. Can you explain which file is to be modified exactly please ? TY a lot

**Comment by ernst77** [comment]
> @ErnestStaug I have the same problem. Can you explain which file is to be modified exactly please ? TY a lot

It depends how you generate pdf, do not import css/fonts or anything via url in HTML, generate static code in your HTML that you are trying to convert to PDF. I would even convert everything to base64 (images/fonts/svgs) so there is no need to load anything from URLs...
