### ISSUE TITLE
how to listen page by on？

### ISSUE THREAD

**Issue by yangweijie** [nesk/puphpeteer#33]
when i simulate to login some website to get cookie, there comes alert dialog. how to write like js code below same with php？

	page.on('dialog', async dialog => {
	    console.log(dialog.message());
	    await dialog.dismiss();
	    // await browser.close();
	});

**Comment by nesk** [comment]
See the documentation about [evaluated functions](https://github.com/nesk/puphpeteer#evaluated-functions-must-be-created-with-jsfunction).

**Comment by tfedor** [comment]
I checked the documentation but I think I still don't understand how this is supposed to work.

I understand that I have to use JsFunction, I think I know how to create one, but how do I get back the result in PHP?

```
$function = JsFunction::createWithAsync()
    ->parameters(["response"])
    ->body('return response.status();');

$page->on("response", $function);
```

how do I get the status in PHP? Is there an example I have missed? If it's not, can it be please created?

**Comment by nesk** [comment]
I should document this. You can listen for an event and react to it, however it’s currently impossible to transmit a value to PHP from a JS event.

**Comment by kids-return** [comment]
How to achieve this, whether to consider adding afterwards

**Comment by kids-return** [comment]
I tried to do this, but something went wrong.
```php
        $function = JsFunction::create(['request'], "
            fs = require('fs');
            fs.writeFileSync('request.txt', request.url());
        ");
        $page->on('requestfailed', $function);
```

PHP Fatal error:  Uncaught Nesk\Rialto\Exceptions\Node\FatalException: require is not defined in /Users/lixiang/Documents/data/wwwroot/yii3/vendor/nesk/rialto/src/ProcessSupervisor.php:307

**Comment by kids-return** [comment]
```js
    page.on('requestfailed', function (request) {
        fs = require('fs');
        fs.writeFileSync('request.txt', request.url());
    });
```
In nodejs, this works fine

**Comment by nesk** [comment]
This is because JS functions in PuPHPeteer are created with the `Function` constructor, your last example would look like this if written with PuPHPeteer:

```js
page.on('requestfailed', new Function('request', `
    fs = require('fs');
    fs.writeFileSync('request.txt', request.url());
`));
```

This will fail because the body of the function doesn't have access [to the `module` scope](https://nodejs.org/api/modules.html#modules_the_module_scope), but only to the global one.

I agree this is an issue and should be fixed, I've created an issue for this: nesk/rialto#19

**Comment by truong8487** [comment]
Please resolve this issue, Mr Nesk and All!The example above , i till dont understand.
Let show a example about page.on when use with puphpeteer.
Thank u so much!
