### ISSUE TITLE
Allow to set chrome executable path

### ISSUE THREAD

**Issue by napsio** [nesk/puphpeteer#40]
Can you add the option to set the executable path of chrome?

**Comment by nesk** [comment]
This is done [with Puppeteer's API](https://pptr.dev/#?product=Puppeteer&version=v1.12.2&show=api-puppeteerlaunchoptions):

```php
use Nesk\Puphpeteer\Puppeteer;

$puppeteer = new Puppeteer;
$browser = $puppeteer->launch([
    'executablePath' => '/path/to/chrome',
]);
```

**Comment by napsio** [comment]
Thanks
