### ISSUE TITLE
[Question] How to do an analog for page.waitFor(dev.myElementHasSpawned).then(... ?

### ISSUE THREAD

**Issue by neorganic** [nesk/puphpeteer#49]
How could I do this with puphpeteer? The docs were unclear.

 ```   
 await page.waitFor('dev.myElementHasSpawned').then( async() => {

// Ok now let's do some stuff here

});
```

**Comment by nesk** [comment]
You can't for the moment, this requires [a new feature to be developed](https://github.com/nesk/rialto/issues/13).
