### ISSUE TITLE
$puppeteer->launch(['headless' => false]) not working

### ISSUE THREAD

**Issue by gaoxiangbo9527** [nesk/puphpeteer#51]
I want see the chromium, So i write this code:

$puppeteer = new Nesk\Puphpeteer\Puppeteer;
$browser = $puppeteer->launch(['headless' => false]);
$page = $browser->newPage();
$page->goto('https://example.com');
echo $page->content();

I got the right output, but i didn't see the chromium。

My development environment is:
php 7.1.18 (wampserver)
node 10.15.3
windows 10

Does anyone have the same problem as me?

**Comment by ping-xiong** [comment]
same problem with you in Windows 7

**Comment by nesk** [comment]
I can be wrong but I don't think this is an issue related to my project (I can't really see how I could mess up this option). Can you try the same test but using Puppeteer directly, in JS? If the GUI doesn't show up, it isn't related to my project and you will have to create an issue directly [on Puppeteer's bug tracker](https://github.com/GoogleChrome/puppeteer/issues).

**Comment by VALIER255** [comment]
idem for me.

**Comment by VALIER255** [comment]
Seems to work fine now.

**Comment by nesk** [comment]
Due to difficulties to reproduce, Windows is not officially supported. Please, replicate the same latency under a Unix system and then I will look at this, thank you.
