### ISSUE TITLE
Howto select elements with next work

### ISSUE THREAD

**Issue by stanolacko** [nesk/puphpeteer#54]
Hi, this is help request.
How to get element and read and work with them like getAttribute etc.
I found solution for read getProperty in #5 .
Example:
`$divs = $page->querySelectorAll('div');
foreach($divs as $div) {
    $attribute = $div->getAttribute('data-value');
    ....
}
`
Thanks

**Comment by nesk** [comment]
You need to use `evaluate` for this, [here's an example in JS](https://github.com/GoogleChrome/puppeteer/issues/1451#issuecomment-346713034).

**Comment by stanolacko** [comment]
Jes I know, it's possible to handle with JS.
But PuPHPeteer is bridge between PHP and Pupeteer / JS, where will be realy great, when it will be element also accessible from PHP
Something like:
'$divs = $page->querySelectorAll('div'); foreach($divs as $div) { $attribute = JSFunction::createWithScope(['element'=>$div])->body('return element.getAttribute('data-value');' }
But it not works with string or json object, but not with result og querySelectorAll ;-(

**Comment by nesk** [comment]
PuPHPeteer is nearly as capable as Puppeteer, code evaluation is possible, you just had to translate the JS example I gave you to PHP:

```php
$callback = JsFunction::createWithParameters(['element'])
	->body("return element.getAttribute('data-src')");

$element->evaluate($callback);
```

**Comment by dahousecat** [comment]
After reading this I'm still not sure how to loop over an array returned from querySelectorAll and finding it hard to find any good code examples anywhere online.

I can see from the documentation that this is a valid line:

`$divs = $page->querySelectorAll('div');`

So how do I loop over the divs?

In your example what does argument 'element' mean within createWithParameters? Is this a selector? Are there any other examples of this that make the syntax clearer?

Also where to you initiate the variable $element?
