### ISSUE TITLE
Wait for page to fully loaded after click event

### ISSUE THREAD

**Issue by slier81** [nesk/puphpeteer#56]
```
$puppeteer = new Puppeteer;

$browser = $puppeteer->launch( [
	'args' => [ '--no-sandbox' ],
	'headless' => true,
	'ignoreHTTPSErrors' => true
] );

$page = $browser->newPage();
$page->goto( $query_params['url'], [ 'waitUntil' => 'networkidle0' ] );

$page->type( '[formcontrolname="username"]', 'username' );
$page->type( '[formcontrolname="password"]', 'password' );
$page->click( '[type="submit"]' );

$page->waitForNavigation(); //shoudl be using this, but from your github issue, it seems that this method cannot be reliably use

$page->screenshot( [ 'path' => 'capture.png', 'fullPage' => true ] );
$browser->close();
```

 I want to wait for the request (after clicking the submit) to fully loaded and after that take the screenshot. So what i should do after the code `$page->click( '[type="submit"]' )`, in order to achieve that?

Based on issue [#4](https://github.com/nesk/puphpeteer/issues/4), u stated that `$page->waitForNavigation()` is not working at the moment, and you suggest to use [go to option](https://pptr.dev/#?product=Puppeteer&version=v1.6.0&show=api-pagegotourl-options)

Problem is, im navigating without using the `goto` method but instead using the `click` event

**Comment by liamcharmer** [comment]
@slier81 not that Im able to answer this, but do you find that the waitUntil works with the goto? I find i always come across errors / hanging with it.

**Comment by slier81** [comment]
@liamcharmer i never tried with `waitUntil`, currently im just hacking it with  php `sleep` function just to make sure, browser properly render the page

**Comment by nesk** [comment]
Like you said, this issue is related to #4. Unfortunately I have no solution for this at the moment, nesk/rialto#13 could fix this but I didn't find some time to work on it.

Closing since it's a duplicate.
