### ISSUE TITLE
Screenshot idle timeout has been reach

### ISSUE THREAD

**Issue by liamcharmer** [nesk/puphpeteer#57]
**Describe the bug**
When trying to do the screenshot, it sometimes comes with a 

Nesk\Rialto\Exceptions\Node\FatalException: The idle timeout has been reached. in /var/www/api.streetify.app/vendor/nesk/rialto/src/ProcessSupervisor.php:304

**Reproducible example**
```php
$page->screenshot()
```

**Expected behavior**
The screenshot is made and no errors appear.

**Comment by nesk** [comment]
Seems like a Puppeteer bug, could you try to reproduce this in pure JS?
