### ISSUE TITLE
Method to get current PuPHPeteer version

### ISSUE THREAD

**Issue by stanolacko** [nesk/puphpeteer#58]
This is feature request:

Catch window.alert() is not supported in current version.
I hope so in future versions will be supported, 

So is it possuble to get current version of PuPHPeteer?

Reason: When version will be changed, I'm able to create assert of version changed to check if there is any progress in this or maybe in other issues.

Thnaks.

**Comment by nesk** [comment]
[Use Composer to get the package version.](https://stackoverflow.com/a/48837257/1513045)

**Comment by stanolacko** [comment]
Question was how to get version number directly from PHP.

**Comment by nesk** [comment]
And I gave you a solution for that, or maybe I didn't understand what you want?
