### ISSUE TITLE
Binary data problem

### ISSUE THREAD

**Issue by Vincz** [nesk/puphpeteer#60]
Binary data returned are invalid

Here two examples, one in JS & one in PHP.

```js
const puppeteer = require("puppeteer");
const fs = require("fs");

const grab = async () => {
  const browser = await puppeteer.launch({
    args: ["--no-sandbox"],
    headless: true
  });
  const page = await browser.newPage();

  const s = await page.goto(
    "https://www.google.fr/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
  );
  fs.writeFileSync("./test_js.png", await s.buffer());
  await browser.close();
};

grab();
```

and

```php
<?php
require_once __DIR__.'/vendor/autoload.php';

use Nesk\Puphpeteer\Puppeteer;

$puppeteer = new Puppeteer();
$browser = $puppeteer->launch([
    'args' => [ '--no-sandbox' ],
    'headless' => true
]);

$page = $browser->newPage();
$s = $page->goto("https://www.google.fr/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png");
file_put_contents('./test_php.png', $s->buffer());
$browser->close();
```

The one in JS works and `test_js.png` is a valid PNG.
The one in PHP fails as `test_php.png` is not valid. 

It seems to be an encoding problem as the resulting image with the PHP version contains `EF BF BD`. Maybe in the communication between the PHP and JS process..

**Comment by nesk** [comment]
I should document this, you cannot use binary data for screenshots, you must retrieve them [using the base64 encoding](https://pptr.dev/#?product=Puppeteer&version=v1.19.0&show=api-pagescreenshotoptions).

**Comment by Vincz** [comment]
Yes... but I want to get the original content of the opened image via the `buffer` method, not a screenshot.
But the buffer method doesn't have the `base64 encoding` option (see [here](https://pptr.dev/#?product=Puppeteer&version=v1.19.0&show=api-responsebuffer)).

**Comment by nesk** [comment]
Woops, sorry, I read too fast and thought you wanted to take a screenshot.

However, there is a simple solution, the `Buffer` class has a `toString` method with an `encoding` parameter. You can probably write this:

```php
$base64 = $s->buffer()->toString('base64');
file_put_contents('./test_php.png', base64_decode($base64));
```

**Comment by Vincz** [comment]
Awesome. Thank you!
