### ISSUE TITLE
Can I set HTML directly instead of goto ($url)?

### ISSUE THREAD

**Issue by smz-web** [nesk/puphpeteer#62]
我是否可以直接设置html,而不是goto($url)?
例如:
$Puppeteer::html($html)
直接设置html，我需要一个协程的Curl来代替goto($url),它的速度太慢了。
谢谢你!

Can I set HTML directly instead of goto ($url)?
For example:
Puppeteer:: HTML ($html)
To set HTML directly, I need a coordinator Curl to replace goto ($url), which is too slow.
Thank you!

**Comment by nesk** [comment]
This could be done by using [setContent()](https://pptr.dev/#?product=Puppeteer&version=v5.3.0&show=api-pagesetcontenthtml-options).
