### ISSUE TITLE
cannot download file

### ISSUE THREAD

**Issue by rvladynskyi** [nesk/puphpeteer#64]
afrer I use $page->pdf()
getting error

Protocol error (Page.printToPDF): PrintToPDF is not implemented in /Users/romanvladynskyi/Projects/fame10/scripts/SUS/vendor/nesk/rialto/src/ProcessSupervisor.php:307
Any ideas how to download file will be helpfull

**Comment by giancanuz** [comment]
if you call
```

$page->pdf(["path" => public_path('page.pdf')]);
response()->download(public_path("page.pdf"))->deleteFileAfterSend(true);

```

you should get the download response

**Comment by nesk** [comment]
See puppeteer/puppeteer#1829
