### ISSUE TITLE
using headless mode is taking forever

### ISSUE THREAD

**Issue by fuxifex** [nesk/puphpeteer#72]
I've tried the default sample for taking a screenshot but it takes about 30 seconds and will timeout and throw an error.

I changed the headless parameter as following:
$browser = $puppeteer->launch([
    'headless' => false
]);

and it works immidately without problems.

My environment
 - OS: Windows 10
 - Node version: 11.0.0.
 - Latest Xampp using PHP version 7.3.12

Any ideas what could be wrong?

**Comment by hdvianna** [comment]
I had the same issue. I solved by installing node packages in a different way.
Instead of  `npm install @nesk/puphpetee` I performed a `npm install puppeteer`, `npm install lodash` and `npm install @nesk/rialto`.

**Comment by nesk** [comment]
Due to difficulties to reproduce, Windows is not officially supported. Please, replicate the same latency under a Unix system and then I will look at this, thank you.
