### ISSUE TITLE
Skipping Cloudflare protection with Puppeteer in PHP

### ISSUE THREAD

**Issue by z3nth10n** [nesk/puphpeteer#76]
I'm having problems with this library. I had a problem with a Cloudflare protection on a forum that I want to scrap and I must wait Javascript to redirect before executing anything, but I have no clue about what to do. 

This is my code:

```php
function getContents($url) {
        $puppeteer = new Puppeteer();
        $browser = $puppeteer->launch([
                'args' => ['--no-sandbox', '--disable-setuid-sandbox']
        ]);

        $page = $browser->newPage();
        $response = $page->goto($url);
        $contents = $page->content();

        return $contents;
}
```

Actually I have a delay of 5 seconds but I'm not sure if Javascript is executing correctly. I'm using ReactPHP Event Loop to check the current HTTP status, but this is always 503...

```php
function getLoop($response, $browser) {
    $loop = React\EventLoop\Factory::create();

    $loop->addPeriodicTimer(5, function () use($response) {
        var_dump($response->headers());
    });

    return $loop;
}
```

`getLoop($response, $browser)->run();`

Due to lack of documentation I can't continue, I don't know where exactly to search for information.

**Comment by heikokrebs** [comment]
@z3nth10n did you found any solution?

**Comment by z3nth10n** [comment]
Yes, using sleep(xxx) where xxx is the number of seconds that you need to wait. Javascript is enabled by default, you need to wait before getting any source code. If everything goes well you should get the right source code.

**Comment by heikokrebs** [comment]
> Yes, using sleep(xxx) where xxx is the number of seconds that you need to wait. Javascript is enabled by default, you need to wait before getting any source code. If everything goes well you should get the right source code.

Ah! I will have a look.
Do you have any sample code for me if i struggle to get it running? Would be great!

**Comment by z3nth10n** [comment]
Ok sorry, I did it by incresing read-timeout parameter, look: https://github.com/uta-org/smf-hook-discord-bot/blob/bd5fe7760a389e5d4ef1c2a307c10597b8998c47/funcs/dom.funcs.php#L54-L72

**Comment by heikokrebs** [comment]
> Ok sorry, I did it by incresing read-timeout parameter, look: https://github.com/uta-org/smf-hook-discord-bot/blob/bd5fe7760a389e5d4ef1c2a307c10597b8998c47/funcs/dom.funcs.php#L54-L72

Thanks a lot for your reply!
Its not working for me with a `sleep(xx)` and read_timeout parameter. Still only get the JS back and the JS-Redirect isnt followed.
Never worked with the react loop - is it any different?

If you have any hint - would be great!

Stay healthy!

**Comment by heikokrebs** [comment]
@z3nth10n 

> Ok sorry, I did it by incresing read-timeout parameter, look: https://github.com/uta-org/smf-hook-discord-bot/blob/bd5fe7760a389e5d4ef1c2a307c10597b8998c47/funcs/dom.funcs.php#L54-L72

Thanks a lot for your reply!
Its not working for me with a `sleep(xx)` and read_timeout parameter. Still only get the JS back and the JS-Redirect isnt followed.
Never worked with the react loop - is it any different?

If you have any hint - would be great!

Stay healthy!

**Comment by aliyazal** [comment]
> 
> 
> Ok sorry, I did it by incresing read-timeout parameter, look: https://github.com/uta-org/smf-hook-discord-bot/blob/bd5fe7760a389e5d4ef1c2a307c10597b8998c47/funcs/dom.funcs.php#L54-L72

Hello, you can use waitforselector, working for me
For example:
```
<?php
 use Nesk\Puphpeteer\Puppeteer;
 use Nesk\Puphpeteer\Resources\ElementHandle;
 $puppeteer = new Puppeteer([
]);
 $browser = $puppeteer->launch([
    'ignoreHTTPSErrors' => true,
    'args' => ['--no-sandbox', '--disable-setuid-sandbox'],
]);
 
 $page = $browser->newPage();
 $url = "https://www.example.com";
 $page->goto($url, [
    'waitUntil' => 'networkidle0',
]);
 $page->waitForSelector("#example");
 $page->screenshot(['path' => 'screen.png']);
 $browser->close();
```

**Comment by nesk** [comment]
Closing since a solution is provided.
