### ISSUE TITLE
Can't figure it out how to use puphpeteer correctly

### ISSUE THREAD

**Issue by khrisnagunanasurya** [nesk/puphpeteer#81]
I already saw this [answer](https://github.com/nesk/puphpeteer/issues/54#issuecomment-508392987), but I can't make it work, 

```
$browser = (new Puppeteer())->launch();
$page = $browser->newPage();
$page->goto('https://website.com/product_detail.html');
$page->querySelectorAll('.product-info-main .price-container .price-wrapper');

$callback = JsFunction::createWithParameters(['element'])
        ->body("return element.getAttribute('data-price-amount')");
$show = $page->evaluate($callback);

dump($show);
$browser->close();
```

I already tried change the element name using the query selector, but it doesnt work, can someone help me? because the documentation is not clear enough for me, thanks

**Comment by ObaydaAlesawi** [comment]
@khrisnagunanasurya can you please explain how you solved that?
