### ISSUE TITLE
Should throw descriptive error if node version is < 8

### ISSUE THREAD

**Issue by famouspotatoes** [nesk/puphpeteer#86]
When I tried running with node v6 installed, I received a generic fatal exception:
```
Unexpected identifier
```

Turns out I just needed to update my node version - but it would be useful to have an exception handling check to determine if the cause is an outdated node installation.

**Comment by nesk** [comment]
This is not the role of PuPHPeteer, NPM should do this [when reading the configuration of the package](https://github.com/nesk/puphpeteer/blob/6fa2ebed4cf7d808c1e14c621687ec19ad3ecdb9/package.json#L22).
