### ISSUE TITLE
puphpeter can't used in swoole process mode

### ISSUE THREAD

**Issue by shuqiangzhou** [nesk/puphpeteer#88]
puphpeteer work in  symfony/process:^4 + php72 + swoole:^4 +hyperf:last(it's use symfony/process:^v5,I require to symfony/process:^4)
-  for test proc_open functiuon ...

![2020-04-11 22-48-10 的屏幕截图](https://user-images.githubusercontent.com/26402118/79047055-f77de780-7c46-11ea-99e0-0b29211cde2c.png)
![2020-04-11 22-49-00 的屏幕截图](https://user-images.githubusercontent.com/26402118/79047057-f947ab00-7c46-11ea-921b-9530f13ccc36.png)
it's work well.

-for test puphpeteer in application
![2020-04-11 22-56-46 的屏幕截图](https://user-images.githubusercontent.com/26402118/79047196-c8b44100-7c47-11ea-9fd7-f98e3b5f6385.png)
![2020-04-11 22-56-54 的屏幕截图](https://user-images.githubusercontent.com/26402118/79047197-ca7e0480-7c47-11ea-82c8-1cb12124adb4.png)
it's can't work,how i cat to do and it's bug??

**Comment by nesk** [comment]
Fixed in nesk/rialto v1.4.0

**Comment by shuqiangzhou** [comment]
> Fixed in nesk/rialto v1.4.0

update to nesk/rialto v1.4.0,
This problem still exists

**Comment by shuqiangzhou** [comment]
hi,I'm very sorry Problem description error,the Problem worked in  process it well,but work Coroutine it fall,today I want test it's worked Coroutine,is's true.
![2020-04-13 10-13-50 的屏幕截图](https://user-images.githubusercontent.com/26402118/79086680-7ff7a780-7d6f-11ea-9527-82df0f9178c6.png)

**Comment by shuqiangzhou** [comment]
hi,I'M disabled swoole process $enableCoroutine=>false and disabled swoole\Runtime::enableCoroutine =>false,it's work well
![2020-04-13 10-58-27 的屏幕截图](https://user-images.githubusercontent.com/26402118/79088628-bafcd980-7d75-11ea-981a-cc2e9ace958a.png)
