### ISSUE TITLE
FileChooser Support

### ISSUE THREAD

**Issue by dannydinges** [nesk/puphpeteer#89]
Is there support for FileChooser? If so does anyone have an example to utilize it?

**Comment by JWprogrammer** [comment]
Hello.
**You can use the [`uploadFile`](https://pptr.dev/#?product=Puppeteer&version=main&show=api-elementhandleuploadfilefilepaths) method in PuPHPeteer:**

```PHP
$page->querySelector('input#selector')->uploadFile('path/to/file');
```

If this doesn't work, just make the input element visible on the page, like this:
```PHP
$page->evaluate(JsFunction::createWithBody("
    const el = document.querySelector('input#selector');
    el.setAttribute('style', 'display: block !important; visibility: visible !important; position: fixed; top: 0; left: 0; z-index: 99999;');
"));
```
