### ISSUE TITLE
Listeners

### ISSUE THREAD

**Issue by john-f-chamberlain** [nesk/puphpeteer#9]
When attempting to do something such as

```
        $page->_client->on("Security.certificateError", function ($event) use ($page) {
            $page->_client->send('Security.handleCertificateError', [
                "eventId" => $event->eventId,
                "action"  => "continue"
            ]);
        });
```

I receive the following error:
```
Nesk \ Rialto \ Exceptions \ Node \ FatalException
"listener" argument must be a function
```

Is there a way to implement listeners using this bridge, or should I stick with writing a node script and then just referencing that from within my PHP scripts?

**Comment by nesk** [comment]
The event callback must be a JS function because it will be executed in the browser context, so you must use [the `JsFunction` class](https://github.com/nesk/puphpeteer#evaluated-functions-must-be-created-with-jsfunction).

Tell me if you encounter issues with it or if you struggle to understand how to use it.

**Comment by john-f-chamberlain** [comment]
Thank you for the quick reply.

I'm not certain how I would implement the above example using the JsFunction class as I am referencing the "$page" PHP object, is there a way to reference the "page" object in a JavaScript function?

Would you be able to provide an example using my code above? Basically I'm trying to get chrome to ignore all invalid SSL certificates and just load the page anyway. This code is what works in pure node:
```
await page._client.on('Security.certificateError', event => {
    page._client.send('Security.handleCertificateError', {
      eventId: event.eventId,
      action: 'continue' // ignore error and continue request
    });
  });
```

**Comment by nesk** [comment]
Ooh, I've never thought about using resources inside JS functions! Actually, I'm not sure this is feasible, but I've opened an issue on Rialto's repository to remember myself to dig into this.

Sorry, but for the moment I think you will have to create your own JS script and run it with PHP. 😞

**Comment by john-f-chamberlain** [comment]
Not a problem at all; I actually already have an entirely functional Node.js version of my script. :) I was already calling it in a Laravel application, but was hoping to be able to keep more of the logic in one location rather than having them broken out. 

Thanks again!

**Comment by nesk** [comment]
Yeah, I understand, the goal of this package is clearly to keep the logic in the same files. I hope I will be able to support resources in JS functions, I will notify you once it will be ready. 🙂

**Comment by nesk** [comment]
Good news @john-f-chamberlain: now you can pass Node resources in JS functions! 😉
