### ISSUE TITLE
[Question/Feature Request] Playwright Support, an alternative for Puppeteer

### ISSUE THREAD

**Issue by ThaDaVos** [nesk/puphpeteer#93]
I was wondering as this package functions like a bridge between Puppeteer and PHP, would it be possible to use Playwright, an alternative for Puppeteer with a mostly identical API, instead of Puppeteer?

Any idea what changes need to be made to get it working?

**Comment by octoper** [comment]
I think this needs to be in a different package.

**Comment by nesk** [comment]
Yes it's possible! This is why I've created [Rialto](https://github.com/nesk/rialto/), the PuPHPeteer repository is only an implementation of Rialto and you can create another implementation.

See this tutorial: https://github.com/nesk/rialto/blob/dev/docs/tutorial.md
And you can also check the code of PuPHPeteer: https://github.com/nesk/puphpeteer/tree/dev/src

ANd yes, this should be done in a new package.
