### ISSUE TITLE
Use Pest for testing

### ISSUE THREAD

**Issue by octoper** [nesk/puphpeteer#96]
Use [Pest](https://github.com/pestphp/pest/) framework for testing.
It makes the tests much cleaner and understandable to everyone.

**Comment by nesk** [comment]
As I said via email, I will not accept a rewrite of the tests from PHPUnit to Pest. This is not something that needs to be done. It's exciting yes, because Pest is a shiny new tool. But today, Rialto and PuPHPeteer need some work on their internals, not on their test runner.
